### ISSUE TITLE
Timetravel miner for Machinecoin

### ISSUE THREAD

**Issue by goodthebest** [machinecoin-project/machinecoin-core#13]
Is there any timetravel miner you would recommend, any ccminer fork specifically for timetravel algo or any other miner for linux/ubuntu OS?

**Comment by Nico205** [comment]
Sorry, for the late reply...didn't noticed the issue at GitHub nor got a mail.
However, asking for a miner is not very GitHub issue related, but here you go https://github.com/tpruvot/ccminer.

Nico;
