### ISSUE TITLE
socket recv error Connection reset by peer (104)

### ISSUE THREAD

**Issue by cipig** [machinecoin-project/machinecoin-core#36]
Updated wallet to commit 77559081a3d3ceeb91ea4d5810fe37f6fa75ee51 and it stopped syncing. All i see in debug.log are lots of `socket recv error Connection reset by peer (104)`

**Comment by cipig** [comment]
reverted back to branch 0.16, will stay on this

**Comment by Nico205** [comment]
Hey there,

this bug should be fixed with the codebase ready at "master".
New releases will get uploaded ASAP.

Friendly Regards
Nico
