### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by 86b** [machinecoin-project/machinecoin-core#37]
There is quite a memory leak on Machinecoin's wallet across all OS's - please be advised.  This is directly affecting service node support for Machinecoin on Blocknet's decentralized exchange infrastructure.

**Comment by Nico205** [comment]
Hey there,
we're aware of this leak and it should be fixed with the codebase at master.
New releases will get uploaded ASAP.

Feel free to test, if the memory leak still exists. Thanks!

Friendly Regards
Nico
